[package]
name = "auth_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.4.2", default-features = false }
diesel = { version = "2.0.0", features = ["postgres", "chrono", "uuid"] }
diesel_migrations = "2.0.0"
serde = { version = "1.0.130", features = ["derive"] }
uuid = { version = "1.1.2", features = ["serde", "v4"] }
argon2 = "0.2.1"
dotenvy = "0.15"
dotenv = "0.15.0"
serde_json = "1.0.68"

[dependencies.rocket_contrib]
version = "0.4.7"
default-features = false
features = ["json", "diesel_postgres_pool"]